# Generated by Django 5.2 on 2025-05-16 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_selection", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedRRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("groupindicator", models.CharField(max_length=100)),
                ("controllvariables", models.JSONField()),
                ("mmethod", models.CharField(max_length=50)),
                ("mdistance", models.CharField(max_length=50)),
                ("mreplace", models.BooleanField(default=False)),
                ("mratio", models.IntegerField()),
                ("mcaliper", models.JSONField(blank=True, null=True)),
                ("mcalipervariables", models.JSONField(blank=True, null=True)),
                ("dataset_json", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
