# Generated by Django 5.2 on 2025-05-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_selection", "0002_savedrrequest_delete_choice_delete_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedrrequest",
            name="controllvariables",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="savedrrequest",
            name="groupindicator",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="savedrrequest",
            name="mdistance",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="savedrrequest",
            name="mmethod",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="savedrrequest",
            name="mratio",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="savedrrequest",
            name="mreplace",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
